name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
          
      - name: Terminate server
        continue-on-error: true
        run: pm2 delete MyWebsite

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Start server
        run: pm2 start main.py --name MyWebsite --interpreter python
